# TODO: Make this into a class and allow passing in a dictionary for each value(with defaults)

C3 = 2.0
TARGET_SPECIES_SIZE = 10
COMPATABILITY_DISTANCE_THRESHOLD = 3.0
THRESHOLD_DELTA = 0.3
AVERAGE_WEIGHT_INHERITANCE_PROBABILITY = 0.4
DISABLED_CONNECTION_INHERITANCE_PROBABILITY = 0.75
WEIGHT_CHANGE_PROBABILITY = 0.8
NORMAL_WEIGHT_CHANGE_PROBABILITY = 0.9
